name: Dependency Check Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Restore Maven dependencies cache
      - name: Restore Maven dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-cache-${{ github.run_id }}
          restore-keys: |
            maven-cache-

      # Step 4: Configure unlimited strength crypto policy
      - name: Install Unlimited Strength Crypto
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      # Step 5: Run dependency-check:update-only
      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:11.1.0:update-only -DnvdApiKeyEnvironmentVariable=NVD_API_KEY

      # Step 6: Archive NVD data
      - name: Archive NVD data
        run: |
          tar -czf dependency-check-cache.tar.gz ~/.m2/repository/org/owasp
        continue-on-error: true

      # Step 7: Upload the NVD data
      - name: Upload NVD data
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-cache
          path: dependency-check-cache.tar.gz

      # Step 8: Save updated Maven dependencies cache
      - name: Save updated Maven dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-cache-${{ github.run_id }}
          restore-keys: |
            maven-cache-