name: Dependency Check Update

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 4: Configure unlimited strength crypto policy
      - name: Install Unlimited Strength Crypto
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      # Step 5: Run dependency-check:update-only
      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:update-only

      # Step 6: Archive cache folder
      - name: Archive dependency-check cache
        run: |
          tar -czf dependency-check-cache.tar.gz ~/.m2/repository/org/owasp/dependency-check/
        continue-on-error: true
      - name: Upload cache
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-cache
          path: dependency-check-cache.tar.gz